# Chapter 7: Data-Driven Dynamical Systems

Course title:

**MECH 575T: Data-driven modeling and control (Self-directed)**

Reference text:

**Data-Driven Science and Engineering, by Steve Brunton**

## Contents

1. Computing the DMD

In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from platform import python_version
python_version()

'3.7.5'

In [3]:
plot_dir = 'plots'
if not os.path.exists(plot_dir):
    os.mkdir(plot_dir)

## Computing the DMD

In [17]:
x = np.array(range(6)).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
u, s, vh = np.linalg.svd(x)

In [19]:
u

array([[-0.27472113, -0.96152395],
       [-0.96152395,  0.27472113]])

In [20]:
s

array([7.34846923, 1.        ])

In [21]:
vh

array([[-0.39254051, -0.56077215, -0.7290038 ],
       [ 0.82416338,  0.13736056, -0.54944226],
       [ 0.40824829, -0.81649658,  0.40824829]])